filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
      - /var/log/mysql/mysql.log
      - /var/log/syslog
      - /var/log/ftp.log

output.kafka:
  hosts: ["localhost:9092"]
  topic: "logaggregation"
